allowBuilds:
  '@fabdeh/eslint-config': false
  '@parcel/watcher': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  simple-git-hooks: false
  unrs-resolver: false
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 days
